apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: coverImage-annotation-setting
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: select
      name: coverImgType
      key: coverImgType
      id: coverImgType
      label: 封面图来源
      validation: required
      value: "firstPostImg"
      placeholder: 请选择你的主题
      options:
        - label: 文章获取首图
          value: firstPostImg
        - label: 随机图
          value: randomImg
        - label: 自定义
          value: customizeImg
    - $el: span
      children: "左右标题都建议两个字 比如: 左标题 通讯 | 右标题 交流"
    - $formkit: "text"
      name: "coverImgTitle1"
      label: "封面图-左标题"
    - $formkit: "text"
      name: "coverImgTitle2"
      label: "封面图-右标题"
    - $formkit: "text"
      name: "coverImgColor"
      label: "封面图-配色"
    - $formkit: "attachment"
      name: "coverImgLogo"
      label: "封面图-ICON"